package main.java.me.dniym.audit.model;

public enum AuditCause {
    PLAYER, HOPPER, HOPPER_PICKUP, DROPPER, DISPENSER, FURNACE, BREWING, CRAFTER,
    COPPER_GOLEM, BLOCK_BREAK, VEHICLE_DESTROY, EXPLOSION, PLUGIN, ADMIN_TRANSFER, INSPECTION, UNKNOWN
}
